# Redirect HTTP → HTTPS (prod uniquement) + ACME challenge Certbot
server {
    listen 80;
    server_name vps.lhspla-ci.org;

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
